syntax = "proto3";

package aiserver.v1;

enum DeeplinkType {
  DEEPLINK_TYPE_UNSPECIFIED = 0;
  DEEPLINK_TYPE_PROMPT = 1;
  DEEPLINK_TYPE_SLASH_COMMAND = 2;
}

message CreateDeeplinkRequest {
  DeeplinkType type = 1;
  map<string, string> data = 2;
  bool is_public = 3;
}

message CreateDeeplinkResponse {
  string url = 1;
}

message DeeplinkMetadata {
  string id = 1;
  DeeplinkType type = 2;
  bool is_public = 3;
  string created_by = 4;
  int64 created_at = 5;
}

message GetDeeplinkDataRequest {
  string deeplink_id = 1;
  string encryption_key = 2;
}

message GetDeeplinkDataResponse {
  DeeplinkType type = 1;
  map<string, string> data = 2;
  string created_by = 3;
  int64 created_at = 4;
}

message ListDeeplinksRequest {
  int32 page_size = 1;
  string page_token = 2;
}

message ListDeeplinksResponse {
  repeated DeeplinkMetadata deeplinks = 1;
  string next_page_token = 2;
}

service DeeplinkService {
  rpc CreateDeeplink (CreateDeeplinkRequest) returns (CreateDeeplinkResponse);
  rpc GetDeeplinkData (GetDeeplinkDataRequest) returns (GetDeeplinkDataResponse);
  rpc ListDeeplinks (ListDeeplinksRequest) returns (ListDeeplinksResponse);
}
