syntax = "proto3";

package aiserver.v1;

import "aiserver/v1/utils.proto";

message FastSearchRequest {
  string uuid = 1;
  string query = 2;
}

message FastSearchResponse {
  message Chunk {
    SimpleFileChunk chunk = 1;
    float chunk_score = 2;
    string contents = 3;
  }

  repeated Chunk file_chunks = 1;
}

message MinimalFileHash {
  string relative_workspace_path = 1;
  string hash = 2;
}

message StartFastSearchRequest {
  string uuid = 1;
  CursorPosition cursor_position = 2;
  repeated MinimalFileHash open_tabs = 3;
  repeated MinimalFileHash context_graph_files = 4;
}

message StartFastSearchResponse {
  message MissingFiles {
    repeated string file = 1;
  }

  message Ready {
    bool ready = 1;
  }

  oneof response {
    Ready ready = 1;
    MissingFiles missing_files = 2;
  }
}

service FastSearchService {
  rpc StartFastSearch (StartFastSearchRequest) returns (StartFastSearchResponse);
  rpc FastSearch (FastSearchRequest) returns (FastSearchResponse);
}
