syntax = "proto3";

package aiserver.v1;

import "aiserver/v1/bidi.proto";

message HealthEmptyRequest {
}

message HealthRequest {
  string payload = 1;
  optional bool simulate_error = 2;
}

message HealthResponse {
  string payload = 1;
}

service HealthService {
  rpc Ping(HealthRequest) returns (HealthResponse);
  rpc Unary(HealthEmptyRequest) returns (HealthResponse);
  rpc Stream(HealthRequest) returns (stream HealthResponse);
  rpc StreamSSE(HealthRequest) returns (stream HealthResponse);
  rpc StreamBidi(stream HealthRequest) returns (stream HealthResponse);
  rpc StreamBidiSSE(BidiRequestId) returns (stream HealthResponse);
  rpc StreamBidiPoll(BidiPollRequest) returns (stream BidiPollResponse);
}
