syntax = "proto3";

package aiserver.v1;

message ClearTeamCreditsRequest {
  int32 team_id = 1;
}

message ClearTeamCreditsResponse {
  bool success = 1;
}

message GetTeamCreditsRequest {
  int32 team_id = 1;
}

message GetTeamCreditsResponse {
  optional int32 credit_dollars = 1;
  bool is_override = 2;
  bool is_expired = 3;
  optional int32 config_credit_dollars = 4;
  optional double used_dollars = 5;
}

message SetTeamCreditsRequest {
  int32 team_id = 1;
  int32 credit_dollars = 2;
}

message SetTeamCreditsResponse {
  bool success = 1;
}

service TeamCreditsService {
  rpc GetTeamCredits (GetTeamCreditsRequest) returns (GetTeamCreditsResponse);
  rpc SetTeamCredits (SetTeamCreditsRequest) returns (SetTeamCreditsResponse);
  rpc ClearTeamCredits (ClearTeamCreditsRequest) returns (ClearTeamCreditsResponse);
}
