syntax = "proto3";

package aiserver.v1;

import "agent/v1/diagnostics_exec.proto";
import "aiserver/v1/repository.proto";
import "aiserver/v1/shadow_workspace.proto";
import "aiserver/v1/tools.proto";
import "aiserver/v1/utils.proto";
import "google/protobuf/timestamp.proto";

enum LogLevel {
  LOG_LEVEL_UNSPECIFIED = 0;
  LOG_LEVEL_INFO = 1;
  LOG_LEVEL_DEBUG = 2;
  LOG_LEVEL_WARN = 3;
  LOG_LEVEL_ERROR = 4;
  LOG_LEVEL_FATAL = 5;
}

message CallClientSideV2ToolRequest {
  ClientSideToolV2Call tool_call = 1;
  string root_path = 2;
  string composer_id = 3;
}

message CallClientSideV2ToolResponse {
  ClientSideToolV2Result tool_result = 1;
}

message CallDiagnosticsExecutorRequest {
  string root_path = 1;
  agent.v1.DiagnosticsArgs diagnostics_args = 2;
}

message CallDiagnosticsExecutorResponse {
  agent.v1.DiagnosticsResult diagnostics_result = 1;
}

message CompileRepoIncludeExcludePatternsRequest {
  string root_path = 1;
  SwCompileRepoIncludeExcludePatternsRequest request = 2;
}

message CompileRepoIncludeExcludePatternsResponse {
  SwCompileRepoIncludeExcludePatternsResponse response = 1;
}

message ExecRequest {
  repeated string command = 1;
  string cwd = 2;
  map<string, string> env = 3;
}

message ExecResponse {
  string stdout = 1;
  string stderr = 2;
  int32 exit_code = 3;
}

message GetEnvironmentInfoRequest {
  string root_path = 1;
}

message GetEnvironmentInfoResponse {
  EnvironmentInfo environment_info = 1;
}

message GetExplicitContextRequest {
  string root_path = 1;
}

message GetExplicitContextResponse {
  ExplicitContext explicit_context = 1;
}

message GetFileStatsRequest {
  repeated string absolute_paths = 1;
}

message GetFileStatsResponse {
  message Stat {
    string absolute_path = 1;
    bool path_exists = 2;
    bool is_file = 3;
  }

  repeated Stat file_stats = 1;
}

message GetLinterErrorsRequest {
  repeated string absolute_paths = 1;
  string root_path = 2;
}

message GetLinterErrorsResponse {
  repeated LinterErrors linter_errors = 1;
}

message GetLogsRequest {
  uint32 max_num_logs = 1;
}

message GetLogsResponse {
  repeated LogEntry log_entries = 1;
  bool has_more_logs = 2;
  uint32 num_dropped_logs = 3;
}

message GetMcpToolsRequest {
  string root_path = 1;
  optional string browser_integration_preference = 2;
}

message GetMcpToolsResponse {
  repeated MCPParams.Tool tools = 1;
}

message GetWorkspaceChangesHashRequest {
  string root_path = 1;
  string base_ref = 2;
}

message GetWorkspaceChangesHashResponse {
  string hash = 1;
}

message InstallExtensionsRequest {
  repeated string extensions = 1;
  string devcontainer_directory = 2;
}

message InstallExtensionsResponse {
  repeated string installed = 1;
  repeated string failed = 2;
}

message LogEntry {
  google.protobuf.Timestamp log_timestamp = 1;
  LogLevel log_level = 2;
  string log_data = 3;
  map<string, string> context = 4;
}

message PingRequest {
}

message PingResponse {
}

message ProvideTemporaryAccessTokenRequest {
  string access_token = 1;
}

message ProvideTemporaryAccessTokenResponse {
}

message ReadTextFileRequest {
  string absolute_path = 1;
}

message ReadTextFileResponse {
  string contents = 1;
  bool path_does_not_exist = 2;
  bool was_truncated = 3;
  bool is_not_a_file = 4;
}

message RefreshGitHubAccessTokenRequest {
  string github_access_token = 1;
  string hostname = 2;
}

message RefreshGitHubAccessTokenResponse {
}

message SyncIndexRequest {
  string root_path = 1;
  RepositoryInfo repository_info = 2;
  string path_encryption_key = 3;
  optional double indexing_progress_threshold = 4;
  optional bool async = 5;
}

message SyncIndexResponse {
}

message TrackModelRequest {
  string root_path = 1;
  string absolute_path = 2;
}

message TrackModelResponse {
}

message UpgradeRequest {
}

message UpgradeResponse {
  string version = 1;
  string new_port = 2;
}

message WarmCursorServerRequest {
  string commit = 1;
  int32 port = 2;
  string connection_token = 3;
  string root_path = 4;
}

message WarmCursorServerResponse {
}

message WriteTextFileRequest {
  string absolute_path = 1;
  string new_contents = 2;
  bool get_new_linter_errors = 3;
  string root_path = 4;
}

message WriteTextFileResponse {
  repeated LinterError new_linter_errors = 1;
}

service VmDaemonService {
  rpc SyncIndex (SyncIndexRequest) returns (SyncIndexResponse);
  rpc CompileRepoIncludeExcludePatterns (CompileRepoIncludeExcludePatternsRequest) returns (CompileRepoIncludeExcludePatternsResponse);
  rpc Upgrade (UpgradeRequest) returns (UpgradeResponse);
  rpc Ping (PingRequest) returns (PingResponse);
  rpc Exec (ExecRequest) returns (ExecResponse);
  rpc CallClientSideV2Tool (CallClientSideV2ToolRequest) returns (CallClientSideV2ToolResponse);
  rpc ReadTextFile (ReadTextFileRequest) returns (ReadTextFileResponse);
  rpc WriteTextFile (WriteTextFileRequest) returns (WriteTextFileResponse);
  rpc GetFileStats (GetFileStatsRequest) returns (GetFileStatsResponse);
  rpc GetExplicitContext (GetExplicitContextRequest) returns (GetExplicitContextResponse);
  rpc GetEnvironmentInfo (GetEnvironmentInfoRequest) returns (GetEnvironmentInfoResponse);
  rpc ProvideTemporaryAccessToken (ProvideTemporaryAccessTokenRequest) returns (ProvideTemporaryAccessTokenResponse);
  rpc WarmCursorServer (WarmCursorServerRequest) returns (WarmCursorServerResponse);
  rpc RefreshGitHubAccessToken (RefreshGitHubAccessTokenRequest) returns (RefreshGitHubAccessTokenResponse);
  rpc GetWorkspaceChangesHash (GetWorkspaceChangesHashRequest) returns (GetWorkspaceChangesHashResponse);
  rpc GetDiff (GetDiffRequest) returns (GetDiffResponse);
  rpc GetLinterErrors (GetLinterErrorsRequest) returns (GetLinterErrorsResponse);
  rpc GetLogs (GetLogsRequest) returns (GetLogsResponse);
  rpc InstallExtensions (InstallExtensionsRequest) returns (InstallExtensionsResponse);
  rpc GetMcpTools (GetMcpToolsRequest) returns (GetMcpToolsResponse);
  rpc TrackModel (TrackModelRequest) returns (TrackModelResponse);
  rpc CallDiagnosticsExecutor (CallDiagnosticsExecutorRequest) returns (CallDiagnosticsExecutorResponse);
}
