syntax = "proto3";

package aiserver.v1;

import "google/protobuf/timestamp.proto";

enum WaterfallLogLevel {
  WATERFALL_LOG_LEVEL_UNSPECIFIED = 0;
  WATERFALL_LOG_LEVEL_DEBUG = 1;
  WATERFALL_LOG_LEVEL_INFO = 2;
  WATERFALL_LOG_LEVEL_WARN = 3;
  WATERFALL_LOG_LEVEL_ERROR = 4;
}

enum WaterfallSpanStatusType {
  WATERFALL_SPAN_STATUS_TYPE_UNSPECIFIED = 0;
  WATERFALL_SPAN_STATUS_TYPE_MESSAGE = 1;
  WATERFALL_SPAN_STATUS_TYPE_WARN = 2;
  WATERFALL_SPAN_STATUS_TYPE_ERROR = 3;
}

message WaterfallUpdate {
  google.protobuf.Timestamp timestamp = 1;
  oneof update {
    SpanStart span_start = 2;
    SpanEnd span_end = 3;
    SpanLog span_log = 4;
    SpanStatusUpdate span_status_update = 5;
    SpanUpdate span_update = 6;
  }
}

message SpanStart {
  string span_id = 1;
  optional string parent_span_id = 2;
  oneof span_details {
    GitReposSetupSpanDetails git_repos_setup = 3;
    GitRepoSetupSpanDetails git_repo_setup = 4;
  }
}

message SpanUpdate {
  string span_id = 1;
  oneof span_update {
    GenericLogSpanUpdate generic_log = 2;
  }
}

message SpanEnd {
  string span_id = 1;
}

message SpanLog {
  string span_id = 1;
  google.protobuf.Timestamp timestamp = 2;
  string message = 3;
  WaterfallLogLevel level = 4;
}

message SpanStatusUpdate {
  string span_id = 1;
  google.protobuf.Timestamp timestamp = 2;
  WaterfallSpanStatusType status_type = 3;
  string message = 4;
  optional CallToAction call_to_action = 5;
}

message CallToAction {
  oneof call_to_action {
    OpenUrlCallToAction open_url = 1;
  }
}

message OpenUrlCallToAction {
  string url = 1;
  string button_text = 2;
}

message GitReposSetupSpanDetails {
}

message GitRepoSetupSpanDetails {
  string repo_display_name = 1;
}

message GenericLogSpanUpdate {
  google.protobuf.Timestamp timestamp = 1;
  string message = 2;
  WaterfallLogLevel level = 3;
}
