syntax = "proto3";

package aiserver.v1;

import "google/protobuf/timestamp.proto";

enum WaterfallLogLevel {
  WATERFALL_LOG_LEVEL_UNSPECIFIED = 0;
  WATERFALL_LOG_LEVEL_DEBUG = 1;
  WATERFALL_LOG_LEVEL_INFO = 2;
  WATERFALL_LOG_LEVEL_WARN = 3;
  WATERFALL_LOG_LEVEL_ERROR = 4;
}

enum WaterfallSpanStatusType {
  WATERFALL_SPAN_STATUS_TYPE_UNSPECIFIED = 0;
  WATERFALL_SPAN_STATUS_TYPE_MESSAGE = 1;
  WATERFALL_SPAN_STATUS_TYPE_WARN = 2;
  WATERFALL_SPAN_STATUS_TYPE_ERROR = 3;
}

enum WaterfallSpanEndStatus {
  WATERFALL_SPAN_END_STATUS_UNSPECIFIED = 0;
  WATERFALL_SPAN_END_STATUS_SUCCESS = 1;
  WATERFALL_SPAN_END_STATUS_FAILURE = 2;
  WATERFALL_SPAN_END_STATUS_SKIPPED = 3;
}

enum WaterfallPhaseType {
  WATERFALL_PHASE_TYPE_UNSPECIFIED = 0;
  WATERFALL_PHASE_TYPE_ENVIRONMENT = 1;
  WATERFALL_PHASE_TYPE_CREATE_CLOUD_WORKSPACE = 2;
  WATERFALL_PHASE_TYPE_PROVISION_SANDBOX = 3;
  WATERFALL_PHASE_TYPE_RESTORE_WORKSPACE_FILES = 4;
  WATERFALL_PHASE_TYPE_DOCKER_BUILD = 5;
  WATERFALL_PHASE_TYPE_SETUP_REPOSITORY = 6;
  WATERFALL_PHASE_TYPE_INSTALL_DEPENDENCIES = 7;
  WATERFALL_PHASE_TYPE_RUN_WORKSPACE_SETUP = 8;
  WATERFALL_PHASE_TYPE_START_AGENT_SERVICES = 9;
  WATERFALL_PHASE_TYPE_INSTALL_EXTENSIONS = 10;
  WATERFALL_PHASE_TYPE_COMPLETE = 11;
  WATERFALL_PHASE_TYPE_ACQUIRE_POD = 12;
  WATERFALL_PHASE_TYPE_HYDRATE = 13;
}

message WaterfallUpdate {
  google.protobuf.Timestamp timestamp = 1;
  oneof update {
    SpanStart span_start = 2;
    SpanEnd span_end = 3;
    SpanLog span_log = 4;
    SpanStatusUpdate span_status_update = 5;
    SpanUpdate span_update = 6;
  }
}

message SpanStart {
  string span_id = 1;
  optional string parent_span_id = 2;
  WaterfallPhaseType phase_type = 5;
  optional string fallback_phase_label = 6;
  oneof span_details {
    GitReposSetupSpanDetails git_repos_setup = 3;
    GitRepoSetupSpanDetails git_repo_setup = 4;
  }
}

message SpanUpdate {
  string span_id = 1;
  oneof span_update {
    GenericLogSpanUpdate generic_log = 2;
  }
}

message SpanEnd {
  string span_id = 1;
  WaterfallSpanEndStatus end_status = 2;
}

message SpanLog {
  string span_id = 1;
  google.protobuf.Timestamp timestamp = 2;
  string message = 3;
  WaterfallLogLevel level = 4;
}

message SpanStatusUpdate {
  string span_id = 1;
  google.protobuf.Timestamp timestamp = 2;
  WaterfallSpanStatusType status_type = 3;
  string message = 4;
  optional CallToAction call_to_action = 5;
}

message CallToAction {
  oneof call_to_action {
    OpenUrlCallToAction open_url = 1;
  }
}

message OpenUrlCallToAction {
  string url = 1;
  string button_text = 2;
}

message GitReposSetupSpanDetails {
}

message GitRepoSetupSpanDetails {
  string repo_display_name = 1;
}

message GenericLogSpanUpdate {
  google.protobuf.Timestamp timestamp = 1;
  string message = 2;
  WaterfallLogLevel level = 3;
}
