syntax = "proto3";

package agent.v1;

message CanvasDestroyArgs {
  string canvas_id = 1;
}

message CanvasDestroyResult {
  bool success = 1;
  bool stopped_server = 2;
}

message CanvasGetUrlArgs {
  string canvas_id = 1;
  bool preview = 2;
}

message CanvasGetUrlResult {
  optional string url = 1;
}

message CanvasRegisterArgs {
  string path = 1;
}

message CanvasRegisterError {
  string error = 1;
}

message CanvasRegisterResult {
  oneof result {
    CanvasRegisterSuccess success = 1;
    CanvasRegisterError error = 2;
  }
}

message CanvasRegisterSuccess {
  string canvas_id = 1;
}
