syntax = "proto3";

package agent.v1;

import "agent/v1/agent.proto";
import "agent/v1/background_shell_exec.proto";
import "agent/v1/canvas_exec.proto";
import "agent/v1/computer_use_tool.proto";
import "agent/v1/delete_exec.proto";
import "agent/v1/diagnostics_exec.proto";
import "agent/v1/fetch_exec.proto";
import "agent/v1/grep_exec.proto";
import "agent/v1/ls_exec.proto";
import "agent/v1/mcp_exec.proto";
import "agent/v1/read_exec.proto";
import "agent/v1/record_screen_exec.proto";
import "agent/v1/request_context_exec.proto";
import "agent/v1/shell_exec.proto";
import "agent/v1/subagent_exec.proto";
import "agent/v1/write_exec.proto";

message AbortArgs {
}

message AbortResult {
}

message ExecClientControlMessage {
  oneof message {
    ExecClientStreamClose stream_close = 1;
    ExecClientThrow throw = 2;
    ExecClientHeartbeat heartbeat = 3;
  }
}

message ExecClientHeartbeat {
  uint32 id = 1;
}

message ExecClientMessage {
  uint32 id = 1;
  string exec_id = 15;
  oneof message {
    ShellResult shell_result = 2;
    WriteResult write_result = 3;
    DeleteResult delete_result = 4;
    GrepResult grep_result = 5;
    ReadResult read_result = 7;
    ReadResult redacted_read_result = 29;
    LsResult ls_result = 8;
    DiagnosticsResult diagnostics_result = 9;
    RequestContextResult request_context_result = 10;
    McpResult mcp_result = 11;
    ShellStream shell_stream = 14;
    BackgroundShellSpawnResult background_shell_spawn_result = 16;
    ListMcpResourcesExecResult list_mcp_resources_exec_result = 17;
    ReadMcpResourceExecResult read_mcp_resource_exec_result = 18;
    McpStateExecResult mcp_state_exec_result = 36;
    FetchResult fetch_result = 20;
    RecordScreenResult record_screen_result = 21;
    ComputerUseResult computer_use_result = 22;
    WriteShellStdinResult write_shell_stdin_result = 23;
    ExecuteHookResult execute_hook_result = 27;
    SubagentResult subagent_result = 28;
    ForceBackgroundShellResult force_background_shell_result = 30;
    ForceBackgroundSubagentResult force_background_subagent_result = 31;
    CanvasGetUrlResult canvas_get_url_result = 33;
    CanvasDestroyResult canvas_destroy_result = 34;
    CanvasRegisterResult canvas_register_result = 35;
  }
}

message ExecClientStreamClose {
  uint32 id = 1;
}

message ExecClientThrow {
  uint32 id = 1;
  string error = 2;
  optional string stack_trace = 3;
}

message ExecServerMessage {
  uint32 id = 1;
  string exec_id = 15;
  oneof message {
    ShellArgs shell_args = 2;
    WriteArgs write_args = 3;
    DeleteArgs delete_args = 4;
    GrepArgs grep_args = 5;
    ReadArgs read_args = 7;
    ReadArgs redacted_read_args = 29;
    LsArgs ls_args = 8;
    DiagnosticsArgs diagnostics_args = 9;
    RequestContextArgs request_context_args = 10;
    McpArgs mcp_args = 11;
    ShellArgs shell_stream_args = 14;
    BackgroundShellSpawnArgs background_shell_spawn_args = 16;
    ListMcpResourcesExecArgs list_mcp_resources_exec_args = 17;
    ReadMcpResourceExecArgs read_mcp_resource_exec_args = 18;
    McpStateExecArgs mcp_state_exec_args = 36;
    FetchArgs fetch_args = 20;
    RecordScreenArgs record_screen_args = 21;
    ComputerUseArgs computer_use_args = 22;
    WriteShellStdinArgs write_shell_stdin_args = 23;
    ExecuteHookArgs execute_hook_args = 27;
    SubagentArgs subagent_args = 28;
    ForceBackgroundShellArgs force_background_shell_args = 30;
    ForceBackgroundSubagentArgs force_background_subagent_args = 31;
    CanvasGetUrlArgs canvas_get_url_args = 33;
    CanvasDestroyArgs canvas_destroy_args = 34;
    CanvasRegisterArgs canvas_register_args = 35;
  }
  optional SpanContext span_context = 19;
}

message ExecuteHookArgs {
  ExecuteHookRequest request = 1;
}

message ExecuteHookRequest {
  oneof request {
    PreCompactRequestQuery pre_compact = 1;
    SubagentStartRequestQuery subagent_start = 2;
    SubagentStopRequestQuery subagent_stop = 3;
    PreToolUseRequestQuery pre_tool_use = 4;
    PostToolUseRequestQuery post_tool_use = 5;
    PostToolUseFailureRequestQuery post_tool_use_failure = 6;
  }
}

message ExecuteHookResponse {
  oneof response {
    PreCompactRequestResponse pre_compact = 1;
    SubagentStartRequestResponse subagent_start = 2;
    SubagentStopRequestResponse subagent_stop = 3;
    PreToolUseRequestResponse pre_tool_use = 4;
    PostToolUseRequestResponse post_tool_use = 5;
    PostToolUseFailureRequestResponse post_tool_use_failure = 6;
  }
}

message ExecuteHookResult {
  ExecuteHookResponse response = 1;
}

message SpanContext {
  string trace_id = 1;
  string span_id = 2;
  optional uint32 trace_flags = 3;
  optional string trace_state = 4;
}
