syntax = "proto3";

package agent.v1;

import "agent/v1/agent.proto";
import "agent/v1/agent_store_conflict_exec.proto";
import "agent/v1/background_shell_exec.proto";
import "agent/v1/canvas_diagnostics_exec.proto";
import "agent/v1/computer_use_tool.proto";
import "agent/v1/conversation_search_exec.proto";
import "agent/v1/delete_exec.proto";
import "agent/v1/diagnostics_exec.proto";
import "agent/v1/fetch_exec.proto";
import "agent/v1/grep_exec.proto";
import "agent/v1/hook_additional_context.proto";
import "agent/v1/ls_exec.proto";
import "agent/v1/mcp_allowlist_precheck_exec.proto";
import "agent/v1/mcp_exec.proto";
import "agent/v1/pi_bash_exec.proto";
import "agent/v1/pi_edit_exec.proto";
import "agent/v1/pi_find_exec.proto";
import "agent/v1/pi_grep_exec.proto";
import "agent/v1/pi_ls_exec.proto";
import "agent/v1/pi_read_exec.proto";
import "agent/v1/pi_write_exec.proto";
import "agent/v1/read_exec.proto";
import "agent/v1/record_screen_exec.proto";
import "agent/v1/request_context_exec.proto";
import "agent/v1/shell_allowlist_precheck_exec.proto";
import "agent/v1/shell_exec.proto";
import "agent/v1/smart_mode_classifier_exec.proto";
import "agent/v1/subagent_exec.proto";
import "agent/v1/web_fetch_allowlist_precheck_exec.proto";
import "agent/v1/write_exec.proto";
import "aiserver/v1/utils.proto";

message ExecClientStreamClose {
  uint32 id = 1;
}

message ExecClientThrow {
  uint32 id = 1;
  string error = 2;
  optional string stack_trace = 3;
  optional string error_code = 4;
}

message ExecClientHeartbeat {
  uint32 id = 1;
}

message ExecClientControlMessage {
  oneof message {
    ExecClientStreamClose stream_close = 1;
    ExecClientThrow throw = 2;
    ExecClientHeartbeat heartbeat = 3;
  }
}

message SpanContext {
  string trace_id = 1;
  string span_id = 2;
  optional uint32 trace_flags = 3;
  optional string trace_state = 4;
}

message ExecServerMessage {
  uint32 id = 1;
  string exec_id = 15;
  optional SpanContext span_context = 19;
  optional bool accept_hook_additional_contexts = 55;
  oneof message {
    ShellArgs shell_args = 2;
    WriteArgs write_args = 3;
    DeleteArgs delete_args = 4;
    GrepArgs grep_args = 5;
    ReadArgs read_args = 7;
    ReadArgs redacted_read_args = 29;
    LsArgs ls_args = 8;
    DiagnosticsArgs diagnostics_args = 9;
    RequestContextArgs request_context_args = 10;
    McpArgs mcp_args = 11;
    ShellArgs shell_stream_args = 14;
    BackgroundShellSpawnArgs background_shell_spawn_args = 16;
    ListMcpResourcesExecArgs list_mcp_resources_exec_args = 17;
    ReadMcpResourceExecArgs read_mcp_resource_exec_args = 18;
    McpStateExecArgs mcp_state_exec_args = 36;
    FetchArgs fetch_args = 20;
    RecordScreenArgs record_screen_args = 21;
    ComputerUseArgs computer_use_args = 22;
    WriteShellStdinArgs write_shell_stdin_args = 23;
    ExecuteHookArgs execute_hook_args = 27;
    SubagentArgs subagent_args = 28;
    ForceBackgroundShellArgs force_background_shell_args = 30;
    ForceBackgroundSubagentArgs force_background_subagent_args = 31;
    SubagentAwaitArgs subagent_await_args = 37;
    SmartModeClassifierArgs smart_mode_classifier_args = 38;
    CanvasDiagnosticsArgs canvas_diagnostics_args = 40;
    ShellAllowlistPrecheckArgs shell_allowlist_precheck_args = 41;
    McpAllowlistPrecheckArgs mcp_allowlist_precheck_args = 42;
    WebFetchAllowlistPrecheckArgs web_fetch_allowlist_precheck_args = 43;
    aiserver.v1.GetDiffRequest git_diff_request = 44;
    PiReadExecArgs pi_read_args = 45;
    PiBashExecArgs pi_bash_args = 46;
    PiEditExecArgs pi_edit_args = 47;
    PiWriteExecArgs pi_write_args = 48;
    PiGrepExecArgs pi_grep_args = 49;
    PiFindExecArgs pi_find_args = 50;
    PiLsExecArgs pi_ls_args = 51;
    ShellArgs mini_swe_agent_bash_args = 52;
    ConversationSearchArgs conversation_search_args = 53;
    AgentStoreConflictArgs agent_store_conflict_args = 54;
  }
}

message ExecClientMessage {
  uint32 id = 1;
  string exec_id = 15;
  optional int32 local_execution_time_ms = 39;
  repeated HookAdditionalContext hook_additional_contexts = 45;
  oneof message {
    ShellResult shell_result = 2;
    WriteResult write_result = 3;
    DeleteResult delete_result = 4;
    GrepResult grep_result = 5;
    ReadResult read_result = 7;
    ReadResult redacted_read_result = 29;
    LsResult ls_result = 8;
    DiagnosticsResult diagnostics_result = 9;
    RequestContextResult request_context_result = 10;
    McpResult mcp_result = 11;
    ShellStream shell_stream = 14;
    BackgroundShellSpawnResult background_shell_spawn_result = 16;
    ListMcpResourcesExecResult list_mcp_resources_exec_result = 17;
    ReadMcpResourceExecResult read_mcp_resource_exec_result = 18;
    McpStateExecResult mcp_state_exec_result = 36;
    FetchResult fetch_result = 20;
    RecordScreenResult record_screen_result = 21;
    ComputerUseResult computer_use_result = 22;
    WriteShellStdinResult write_shell_stdin_result = 23;
    ExecuteHookResult execute_hook_result = 27;
    SubagentResult subagent_result = 28;
    ForceBackgroundShellResult force_background_shell_result = 30;
    ForceBackgroundSubagentResult force_background_subagent_result = 31;
    SubagentAwaitResult subagent_await_result = 37;
    SmartModeClassifierResult smart_mode_classifier_result = 38;
    CanvasDiagnosticsResult canvas_diagnostics_result = 40;
    ShellAllowlistPrecheckResult shell_allowlist_precheck_result = 41;
    McpAllowlistPrecheckResult mcp_allowlist_precheck_result = 42;
    WebFetchAllowlistPrecheckResult web_fetch_allowlist_precheck_result = 43;
    aiserver.v1.GetDiffResponse git_diff_response = 44;
    PiReadExecResult pi_read_result = 46;
    PiBashExecResult pi_bash_result = 47;
    PiEditExecResult pi_edit_result = 48;
    PiWriteExecResult pi_write_result = 49;
    PiGrepExecResult pi_grep_result = 50;
    PiFindExecResult pi_find_result = 51;
    PiLsExecResult pi_ls_result = 52;
    ConversationSearchResult conversation_search_result = 53;
    AgentStoreConflictResult agent_store_conflict_result = 54;
    ShellResult mini_swe_agent_bash_result = 55;
  }
}

message ExecuteHookArgs {
  ExecuteHookRequest request = 1;
}

message ExecuteHookResult {
  ExecuteHookResponse response = 1;
}

message ExecuteHookRequest {
  oneof request {
    PreCompactRequestQuery pre_compact = 1;
    SubagentStartRequestQuery subagent_start = 2;
    SubagentStopRequestQuery subagent_stop = 3;
    PreToolUseRequestQuery pre_tool_use = 4;
    PostToolUseRequestQuery post_tool_use = 5;
    PostToolUseFailureRequestQuery post_tool_use_failure = 6;
    BeforeSubmitPromptRequestQuery before_submit_prompt = 7;
    AfterAgentResponseRequestQuery after_agent_response = 8;
    AfterAgentThoughtRequestQuery after_agent_thought = 9;
    StopRequestQuery stop = 11;
  }
}

message ExecuteHookResponse {
  oneof response {
    PreCompactRequestResponse pre_compact = 1;
    SubagentStartRequestResponse subagent_start = 2;
    SubagentStopRequestResponse subagent_stop = 3;
    PreToolUseRequestResponse pre_tool_use = 4;
    PostToolUseRequestResponse post_tool_use = 5;
    PostToolUseFailureRequestResponse post_tool_use_failure = 6;
    BeforeSubmitPromptRequestResponse before_submit_prompt = 7;
    AfterAgentResponseRequestResponse after_agent_response = 8;
    AfterAgentThoughtRequestResponse after_agent_thought = 9;
    StopRequestResponse stop = 11;
  }
}

message ExecStreamElement {
  oneof element {
    ExecClientMessage exec_client_message = 1;
    ExecClientControlMessage exec_client_control_message = 2;
  }
}

service ExecService {
  rpc Exec(ExecServerMessage) returns (stream ExecStreamElement);
}
